### ISSUE TITLE
jade + karma ... unexpected request: GET

### ISSUE THREAD

**Issue by 0101adm** [Swiip/generator-gulp-angular#774] opened 2015-09-11 17:52 UTC
my directive spec is failing because of an unexpected get to fetch the template.

in karma.confg i see...

```javascript
preprocessors: {
      'src/**/*.html': ['ng-html2js']
    }
```
since my partials are .jade, it musnt be loading anything into cache?

**Comment by 0101adm** [comment] 2015-09-11 17:53
just confirmed.

added a file w/ .html extension and it worked.

**Comment by zckrs** [comment] 2015-09-11 17:56
Duplicate of https://github.com/Swiip/generator-gulp-angular/issues/731 ?

**Comment by zckrs** [comment] 2015-09-11 17:57
PR https://github.com/Swiip/generator-gulp-angular/pull/770

**Comment by 0101adm** [comment] 2015-09-11 18:29
temp fix by using ng-jade2js.

my new karma.conf.js

```javascript
'use strict';

var path = require('path');
var conf = require('./gulp/conf');

var _ = require('lodash');
var wiredep = require('wiredep');

function listFiles() {
  var wiredepOptions = _.extend({}, conf.wiredep, {
    dependencies: true,
    devDependencies: true
  });

  return wiredep(wiredepOptions).js
    .concat([
      path.join(conf.paths.tmp, '/serve/app/index.module.js'),
      path.join(conf.paths.src, '/**/*.spec.js'),
      path.join(conf.paths.src, '/**/*.mock.js'),
      path.join(conf.paths.src, '/**/*.html'),
      path.join(conf.paths.src, '/**/*.jade')
    ]);
}

module.exports = function(config) {
  var configuration = {
    files: listFiles(),

    singleRun: true,

    autoWatch: false,

    frameworks: ['jasmine'],

    ngHtml2JsPreprocessor: {
      stripPrefix: 'src/',
      moduleName: 'myapp'
    },

    ngJade2JsPreprocessor: {
      stripPrefix: 'src/',
      moduleName: 'myapp'
    },

    browsers : ['PhantomJS'],

    plugins : [
      'karma-phantomjs-launcher',
      'karma-jasmine',
      'karma-ng-html2js-preprocessor',
      'karma-ng-jade2js-preprocessor'
    ],

    preprocessors: {
      'src/**/*.html': ['ng-html2js'],
      'src/**/*.jade': ['ng-jade2js']
    }
  };

  // This block is needed to execute Chrome on Travis
  // If you ever plan to use Chrome and Travis, you can keep it
  // If not, you can safely remove it
  // https://github.com/karma-runner/karma/issues/1144#issuecomment-53633076
  if(configuration.browsers[0] === 'Chrome' && process.env.TRAVIS) {
    configuration.customLaunchers = {
      'chrome-travis-ci': {
        base: 'Chrome',
        flags: ['--no-sandbox']
      }
    };
    configuration.browsers = ['chrome-travis-ci'];
  }

  config.set(configuration);
};
```

**Comment by zckrs** [comment] 2015-09-15 14:56
In this generator we prefer manage preprocessor inside gulp process instead karma.

So we compile jade partial in folder .tmp and serve them

**Closed by zckrs** 2015-09-15 14:56 UTC
