### ISSUE TITLE
[Question] Proper way to create source maps for javascript

### ISSUE THREAD

**Issue by dereklin** [Swiip/generator-gulp-angular#630] opened 2015-06-22 23:35 UTC
I have added two lines in order to create source maps for my minified javascript.  Is that ok?  Or is there is a more proper way?:

Condensed:
```
...
.pipe($.sourcemaps.init())
...
.pipe($.sourcemaps.write())
...
```

Full:
```
gulp.task('html', ['inject', 'partials'], function () {
  var partialsInjectFile = gulp.src(path.join(conf.paths.tmp, '/partials/templateCacheHtml.js'), { read: false });
  var partialsInjectOptions = {
    starttag: '<!-- inject:partials -->',
    ignorePath: path.join(conf.paths.tmp, '/partials'),
    addRootSlash: false
  };

  var htmlFilter = $.filter('*.html');
  var jsFilter = $.filter('**/*.js');
  var cssFilter = $.filter('**/*.css');
  var assets;

  return gulp.src(path.join(conf.paths.tmp, '/serve/*.html'))
    .pipe($.inject(partialsInjectFile, partialsInjectOptions))
    .pipe(assets = $.useref.assets())
    .pipe($.rev())
    .pipe($.sourcemaps.init()) // added for sourcemaps
    .pipe(jsFilter)
    .pipe($.ngAnnotate())
    .pipe($.uglify({ preserveComments: $.uglifySaveLicense })).on('error', conf.errorHandler('Uglify'))
    .pipe($.sourcemaps.write()) // added for sourcemaps
    .pipe(jsFilter.restore())
    .pipe(cssFilter)
    .pipe($.replace('../../bower_components/bootstrap-stylus/fonts/', '../fonts/'))
    .pipe($.csso())
    .pipe(cssFilter.restore())
    .pipe(assets.restore())
    .pipe($.useref())
    .pipe($.revReplace())
    .pipe(htmlFilter)
    .pipe($.minifyHtml({
      empty: true,
      spare: true,
      quotes: true,
      conditionals: true
    }))
    .pipe(htmlFilter.restore())


    .pipe(gulp.dest(path.join(conf.paths.dist, '/')))
    .pipe($.size({ title: path.join(conf.paths.dist, '/'), showFiles: true }));
});
```

**Comment by Swiip** [comment] 2015-06-23 06:25
Nop this can't work. You added sourcemaps on the JS part you dont have the concat / rename files part. If we dont deliver sourcemaps for dist out of the box is because to my knowledge it's y et not possible with gulp-useref

**Comment by dereklin** [comment] 2015-06-23 16:40
But it seems to work.  Here is my .yo-rc.json:

```
{
  "generator-gulp-angular": {
    "version": "0.12.1",
    "props": {
      "angularVersion": "~1.4.0",
      "angularModules": [
        {
          "key": "animate",
          "module": "ngAnimate"
        }
      ],
      "jQuery": {
        "key": "jquery2"
      },
      "resource": {
        "key": "none",
        "module": null
      },
      "router": {
        "key": "ui-router",
        "module": "ui.router"
      },
      "ui": {
        "key": "bootstrap",
        "module": null
      },
      "bootstrapComponents": {
        "key": "ui-bootstrap",
        "module": "ui.bootstrap"
      },
      "cssPreprocessor": {
        "key": "stylus",
        "extension": "styl"
      },
      "jsPreprocessor": {
        "key": "none",
        "extension": "js",
        "srcExtension": "js"
      },
      "htmlPreprocessor": {
        "key": "none",
        "extension": "html"
      },
      "foundationComponents": {
        "name": null,
        "version": null,
        "key": null,
        "module": null
      },
      "paths": {
        "src": "src",
        "dist": "dist",
        "e2e": "e2e",
        "tmp": ".tmp"
      }
    }
  }
}
```

**Comment by Swiip** [comment] 2015-06-23 16:46
It works ? :) I would be great, I have to test this...

**Comment by wgorder** [comment] 2015-06-30 16:57
yes confirmed it does work.

https://github.com/jonkemp/gulp-useref/issues/64

**Comment by Swiip** [comment] 2015-07-14 14:35
I tried a bit. I got the source map of the bundles but I loose the original files paths. It's already way better than nothing but anyone succeeded to get even the files?

**Comment by zckrs** [comment] 2015-07-28 08:57
Fixed by #672

**Comment by zckrs** [comment] 2015-09-09 11:47
v1.0.0-rc1 released on NPM.

[How to update my project?](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/upgrade-my-current-project.md)

**Closed by zckrs** 2015-09-09 11:47 UTC
Labels: fixed-in-next-release

**Comment by priley86** [comment] 2016-04-21 16:35
Can anyone explain how to get the Webpack/ES6 Babel compiled sourcemaps working in Safari? Safari doesn't seem to pickup the base64 encoded sourcemaps like Chrome does (Chrome displays all sources in the webpack folder for the compiled index.module.js). I don't see this behavior in Safari.

**Comment by priley86** [comment] 2016-04-21 16:47
It appears to work if you change the gulp webpackWrapper in scripts.js to use 'source-map' as opposed to 'inline-source-map'.

`  if(watch) {
    webpackOptions.devtool = 'source-map';
  }`
