### ISSUE TITLE
'gulp watch' not recompiling .ts files on Windows

### ISSUE THREAD

**Issue by psychowood** [Swiip/generator-gulp-angular#901] opened 2015-11-12 10:02 UTC
As per issue subject, the watch task does not seems to recognize TypeScript changes correctly in Windows. Tested on multiple Windows installations (Win7,Win8,Win10). Project was scaffolded yesterday from v1.0.0.

The console seems to be correct (and in line to what is logged on my Mac, which recompiles correctly, tho).

```
[17:31:49] webpack is watching for changes
[BS] [BrowserSync SPA] Running...
[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:3000/
    External: http://10.0.2.15:3000/
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.2.15:3001
 -----------------------------------
[BS] Serving files from: .tmp\serve
[BS] Serving files from: src
[17:32:25] Time: 441ms
          Asset     Size  Chunks       Chunk Names
index.module.js  34.3 kB       0       main
[BS] Reloading Browsers...
[17:32:25] webpack is watching for changes
```

**Comment by ytkj** [comment] 2015-11-12 13:28
The same problem in my environment.
#893 may be a temporary solution, but not a fundamental one.
I think this may be a problem caused by webpack or awesome-typescript-loader...

**Comment by jbrantly** [comment] 2015-11-12 18:40
(somewhat shameless plug) @jasteph reported ts-loader worked, might be worth a try (and help narrow down where the problem lies)

**Comment by ytkj** [comment] 2015-11-12 23:09
s-panferov/awesome-typescript-loader#72 works for me. Try it.

**Comment by Swiip** [comment] 2015-11-18 09:11
Sorry, I don't have a Win env to test that kind of issues. Hope someone of the community could help.

**Comment by craigsh** [comment] 2015-12-02 20:33
Changing package.json to make "awesome-typescript-loader": "~0.15.6" fixes the problem.
Then I had to add an excludes config to the tsconfig.json file:

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs"
  },    
  "exclude": [
      "node_modules",
      "bower_components"
    ]
}

**Comment by AepKill** [comment] 2016-01-14 15:40
@craigsh is right，thanks very much。

**Comment by Swiip** [comment] 2016-03-31 16:32
That should be fixed with the switch on ts-loader in the last release: https://github.com/Swiip/generator-gulp-angular/releases/tag/v1.1.0

**Closed by Swiip** 2016-03-31 16:32 UTC
