### ISSUE TITLE
Building with Resource Files Referenced in Files in Bower Dependencies

### ISSUE THREAD

**Issue by glsee** [Swiip/generator-gulp-angular#474] opened 2015-04-06 16:37 UTC
Right now, there is no handling of resource files that are referenced in the third party libraries installed via Bower when running the `build` command.

E.g. a CSS file that references an image file as a background image of some elements:

After running though `wiredep` and `useref`, in the resulting concatenated CSS the URL of the image is no longer valid because the image is no longer at the relative path originally specified in the library, and the referenced image file does not become part of the build (copied and put alongside with the rest of the build files).

**Comment by Swiip** [comment] 2015-04-07 07:06
There is a special treatment for the font file of Bootstrap but what you're asking seems not easy or even doable to me.

It requires to modify the link wherever this resources are used. It can be CSS, HTML or even some computation on the JS. I'm not sure what we can do...

**Comment by zckrs** [comment] 2015-05-23 07:32
Duplicate of https://github.com/Swiip/generator-gulp-angular/issues/521

**Closed by zckrs** 2015-05-23 07:32 UTC
