### ISSUE TITLE
Yo-tasks for adding components, modules?

### ISSUE THREAD

**Issue by iwuvjhdva** [Swiip/generator-gulp-angular#491] opened 2015-04-16 10:38 UTC
Hi, would be nice to implement such conveniency tasks to add dummy components and modules like this generator has for example https://github.com/leanovate/generator-cc-angular

**Comment by zckrs** [comment] 2015-04-16 10:58
Duplicate of https://github.com/Swiip/generator-gulp-angular/issues/9

A actual workaround: create a file with copy of existing file

**Comment by dereklin** [comment] 2015-04-17 19:55
@zckrs Could you please explain what files I need to manually change to add another module to be depended upon by my main app?  For example, I want to create src/modules/module1.  And my dependency looks like angular.module('myMainApp', ['ngAnimate', 'ngCookies', 'ngTouch', 'ngSanitize', 'ngResource', 'ui.router', 'ui.bootstrap', 'module1']).  Thanks!

**Comment by zckrs** [comment] 2015-05-20 13:03
One thread for one issue.

Please continue in https://github.com/Swiip/generator-gulp-angular/issues/9#issuecomment-103876166

**Closed by zckrs** 2015-05-20 13:03 UTC
Labels: duplicate
