### ISSUE TITLE
File to import not found or unreadable [Sass] Error and gulp serve

### ISSUE THREAD

**Issue by Schurke** [Swiip/generator-gulp-angular#512] opened 2015-04-23 18:19 UTC
I'm running up against a couple of odd issues with gulp serve that have me scratching my head (this may need to be broken into two issues, but they seem to be related)

1. I frequently get a sass error when saving scss files - specifically "file to import not found or unreadable"
2. browser sync reloads the page before the new compiled coffee/js file has been completed and I have to refresh a second time to see changes reflected

It's almost as though the tasks aren't... waiting... for the hard drive to finish... writing. Has this been encountered before? Is there a workaround?

(windows 8, project drive is a physical hard drive)

**Comment by robeasthope** [comment] 2015-04-27 15:22
The sass error is due to a broken file path to one of your scss files or maybe you're trying to compile a css file by accident

**Comment by Schurke** [comment] 2015-04-27 15:57
I'm going to disagree on this one. The error occurs irregularly (succeeds sometimes, fails others).
It's worth saying also that the watch build works ten out of ten times on my SSD.

**Comment by robeasthope** [comment] 2015-04-27 15:59
Fair enough, just trying to cover the easy fixes first - Sounds like you've got a weird one :/

**Comment by Swiip** [comment] 2015-05-04 15:34
If I follow your thoughts, it could be a problem of sequencing between recompilation and browsersync reloads.

In the lasts versions (which version do you use ?) browser sync doesn't manage itself file change detection but it's directly gulp which will trigger browser sync reloads. If you have this new version, I really don't see how it's possible (and how to reproduce easily...)

**Comment by zckrs** [comment] 2015-05-22 15:18
need reply @Schurke .

**Comment by Schurke** [comment] 2015-05-22 15:26
Hi, zckrs and Swiip. At the time I was using the latest version of your package. Interestingly, I heard an anecdote from a colleague using the same generator who encountered the same issue (where they'd generally have to refresh manually post-browser-sync to see changes reflected). Similar hardware setup, where they were using a windows machine with a conventional hard drive.

On my machine, I worked around the issue by moving my project to my SSD. Same project builds without issue every time.

Not likely an issue with browser sync itself - I'm using a wordpress-theme/gulp/browser-sync generator for another project which doesn't exhibit the behaviour at all.

Let me know if you need any more information...

**Comment by Swiip** [comment] 2015-06-06 13:43
This not conclude if you use the version I mention. Can you check if you see a line like this one in your `gulp/styles.js`?

```javascript
.pipe(browserSync.reload({ stream: true }));
```

Also, are you using node-sass or ruby-sass? The ruby version is way more "touchy".

**Comment by Schurke** [comment] 2015-06-13 19:30
Yes - I have precisely that line on 50. 
That said, it's been a while since I looked at the builder. Is there a quick way to check which sass it's using?

**Comment by zckrs** [comment] 2015-06-18 16:11
:tada: Just released v0.12.0 :tada:
Your issue should be fixed. I close but if you can retry your case with a new fresh install of generator you are welcome. Any feedback would be appreciated (positive comments too ^_^).

**Closed by zckrs** 2015-06-18 16:11 UTC
